# Automated Contract Summarization

This notebook generates concise summaries from extracted contract information.

The objective is to reduce the time required to review legal agreements by automatically highlighting key contractual details.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/contracts.csv")

df.head()

,contract_type,borrower,lender,amount,clauses,jurisdiction,obligations,file
0,HEALTH FINANCING AGREEMENT,Julia Miller,FINANCIAL BANK OF AMERICA Inc.,"$42,751.00.","['PURPOSE', 'TERM', 'PAYMENT', 'GUARANTEES', '...","New York, NY",['CLAUSE THREE – PAYMENT: The BORROWER shall p...,Contract_16.pdf
1,MOTORCYCLE FINANCING AGREEMENT,Patricia Hall,FINANCIAL BANK OF AMERICA Inc.,"$36,160.00.","['PURPOSE', 'TERM', 'PAYMENT', 'GUARANTEES', '...","New York, NY",['CLAUSE THREE – PAYMENT: The BORROWER shall p...,Contract_4.pdf
2,HEALTH FINANCING AGREEMENT,Patricia Hall,FINANCIAL BANK OF AMERICA Inc.,"$40,267.00.","['PURPOSE', 'TERM', 'PAYMENT', 'GUARANTEES', '...","New York, NY",['CLAUSE THREE – PAYMENT: The BORROWER shall p...,Contract_5.pdf
3,STUDENT LOAN AGREEMENT,Richard Taylor,FINANCIAL BANK OF AMERICA Inc.,"$56,424.00.","['PURPOSE', 'TERM', 'PAYMENT', 'GUARANTEES', '...","New York, NY",['CLAUSE THREE – PAYMENT: The BORROWER shall p...,Contract_17.pdf
4,HEALTH FINANCING AGREEMENT,Mary Johnson,FINANCIAL BANK OF AMERICA Inc.,"$48,720.00.","['PURPOSE', 'TERM', 'PAYMENT', 'GUARANTEES', '...","New York, NY",['CLAUSE THREE – PAYMENT: The BORROWER shall p...,Contract_7.pdf

In [2]:
def generate_summary(row):

    summary = f"""
Contract Type: {row['contract_type']}

Borrower: {row['borrower']}

Lender: {row['lender']}

Amount: {row['amount']}

Jurisdiction: {row['jurisdiction']}
"""

    return summary.strip()

In [3]:
df["summary"] = df.apply(
    generate_summary,
    axis=1
)

print(df["summary"].iloc[0])

Contract Type: HEALTH FINANCING AGREEMENT

Borrower: Julia Miller

Lender: FINANCIAL BANK OF AMERICA Inc.

Amount: $42,751.00.

Jurisdiction: New York, NY

In [4]:
def generate_intelligent_summary(row):

    summary = f"""
This {row['contract_type']} involves borrower {row['borrower']} and lender {row['lender']}.

The financed amount is {row['amount']} under the jurisdiction of {row['jurisdiction']}.

The contract contains {len(eval(row['clauses']))} major legal clauses and includes contractual obligations related to payment and compliance requirements.
"""

    return summary.strip()

In [5]:
df["intelligent_summary"] = df.apply(
    generate_intelligent_summary,
    axis=1
)

print(
    df["intelligent_summary"].iloc[0]
)

This HEALTH FINANCING AGREEMENT involves borrower Julia Miller and lender FINANCIAL BANK OF AMERICA Inc..

The financed amount is $42,751.00. under the jurisdiction of New York, NY.

The contract contains 8 major legal clauses and includes contractual obligations related to payment and compliance requirements.

In [6]:
summary_df = df[
    [
        "contract_type",
        "borrower",
        "intelligent_summary"
    ]
]

summary_df.head()

,contract_type,borrower,intelligent_summary
0,HEALTH FINANCING AGREEMENT,Julia Miller,This HEALTH FINANCING AGREEMENT involves borro...
1,MOTORCYCLE FINANCING AGREEMENT,Patricia Hall,This MOTORCYCLE FINANCING AGREEMENT involves b...
2,HEALTH FINANCING AGREEMENT,Patricia Hall,This HEALTH FINANCING AGREEMENT involves borro...
3,STUDENT LOAN AGREEMENT,Richard Taylor,This STUDENT LOAN AGREEMENT involves borrower ...
4,HEALTH FINANCING AGREEMENT,Mary Johnson,This HEALTH FINANCING AGREEMENT involves borro...

In [7]:
summary_df.to_csv(
    "../data/processed/contract_summaries.csv",
    index=False
)